---
# Download Drupal using drush (--no-cache prevents checksum error).
# - name: "Drupal: Download Drupal Core."
#   command:
#     drush dl drupal-{{ drupal_core_version }} --no-cache
#     creates={{ drupal_core_path }}/index.php
#     chdir=/var/www

# Download Drupal using Git.
- name: Download Mukurtu using Git to the default location.
  git:
    repo: "{{ drupal_repo_url }}"
    update: "{{ drupal_keep_updated }}"
    dest: "{{ drupal_core_path }}"

- name: Copy Mukurtu settings.php (update after play).
  command: cp /var/www/mukurtu/sites/default/default.settings.php /var/www/mukurtu/sites/default/settings.php

# SEE: https://drupal.org/node/2121849#comment-8413637
- name: Set permissions properly on settings.php.
  file:
    path: "{{ drupal_core_path }}/sites/default/settings.php"
    mode: 0744

- name: Set permissions properly on files directory.
  file:
    path: "{{ drupal_core_path }}/sites/default/files"
    mode: 0777
    state: directory
    recurse: yes

- name: Set SELinux policy on files directory.
  command: chcon -Rt public_content_rw_t /var/www/mukurtu/sites/default/files

- name: Set SELinux Boolean
  command: setsebool -P allow_httpd_anon_write=1

- name: Create firewall rule for port 80
  command: firewall-cmd --zone=public --add-port=80/tcp --permanent

- name: Create firewall rule for port 443
  command: firewall-cmd --zone=public --add-port=443/tcp --permanent

- name: Reload firewalld
  command: firewall-cmd --reload
  
